spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/super_question_lib?useSSL=false&serverTimezone=Hongkong"
    username: "root"
    password: "jiang.141201"
  mail:
    host: smtp.qq.com
    username: 1363646276@qq.com
    password: ueaxhybgheydhaih
  profiles:
    include: redis
mybatis:
  type-aliases-package: com.jxust.qq.superquestionlib.dao.mapper, com.jxust.qq.superquestionlib.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      jxust:
        qq:
          superquestionlib:
            dao:
              mapper: debug